# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(max_length=12)),
                ('birthday', models.DateField()),
                ('rfc', models.CharField(max_length=13)),
                ('curp', models.CharField(max_length=18)),
                ('gender', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=40)),
                ('scholarship', models.CharField(max_length=40)),
                ('ocuppation', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('personale_references', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'verbose_name': 'Client',
            },
        ),
    ]
