# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone_num', models.CharField(max_length=12)),
                ('birthday', models.DateField()),
                ('rfc', models.CharField(max_length=13)),
                ('curp', models.CharField(max_length=18)),
                ('gender', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=40)),
                ('scholarship', models.CharField(max_length=40)),
                ('ocuppation', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('personale_references', models.TextField()),
                ('user_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage', to='clients.Client')),
                ('user_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage', to='vehicles.Vehicle')),
            ],
            options={
                'verbose_name': 'Garage',
                'verbose_name_plural': 'Garages',
            },
        ),
    ]
