# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'MonthlyPayments',
                'verbose_name': 'MonthlyPayment',
            },
        ),
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiclebook', to='clients.Client')),
                ('id_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiclebook', to='vehicles.Vehicle')),
            ],
            options={
                'verbose_name_plural': 'VehicleBookings',
                'verbose_name': 'VehicleBooking',
            },
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='id_vehiclebooking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlypayment', to='vehicles_finances.VehicleBooking'),
        ),
    ]
