# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trademark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='assets/trademark')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('anio', models.DateField(auto_now=True)),
                ('description_short', models.TextField()),
                ('img_front', models.ImageField(blank=True, null=True, upload_to='assets/vehicles')),
                ('img_left', models.ImageField(blank=True, null=True, upload_to='assets/vehicles')),
                ('img_right', models.ImageField(blank=True, null=True, upload_to='assets/vehicles')),
                ('img_back', models.ImageField(blank=True, null=True, upload_to='assets/vehicles')),
                ('trademark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.trademark')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=60)),
                ('airbag', models.BooleanField(default=False)),
                ('sunroof', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('hydraulic_power_steering', models.BooleanField(default=False)),
                ('autoestereo', models.BooleanField(default=False)),
                ('electric_glasses', models.BooleanField(default=False)),
                ('electric_door_locks', models.BooleanField(default=False)),
                ('leather_seats', models.BooleanField(default=False)),
                ('sport_wheels', models.BooleanField(default=False)),
                ('hp', models.CharField(blank=True, max_length=50, null=True)),
                ('engine', models.CharField(blank=True, max_length=7, null=True)),
                ('price', models.FloatField()),
                ('description_long', models.TextField()),
                ('doors_num', models.IntegerField()),
                ('cylinders_num', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.ManyToManyField(to='vehicles.vehicle_color'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_version',
            field=models.ManyToManyField(to='vehicles.Vehicle_version'),
        ),
    ]
